### PR TITLE
chore(dependabot): move rust-toolchain to toml format

### PR DESCRIPTION
**Pull request by ReenigneArcher**
Dependabot only supports toml format for rust-toolchain.

image

You can enable dependabot in this menu.
image

I'd suggest a squash and merge on this to keep the history as one commit.

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
Well, the https://github.com/actions-rs/toolchain?tab=readme-ov-file action is archived and doesn't seem to support the toml format (or maybe I've done something incorrectly)

But dependabot does work like this: https://github.com/ReenigneArcher/pacman-repo-builder/pulls

**Comment by KSXGitHub** [comment]
Interesting. I don't see Rust deprecate non-TOML `rust-toolchain`. The [official documentation](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) doesn't mention any deprecation either. It seems to be an error on dependabot's part.

Well, until this issue is resolved by dependabot team, you may use renovate for now.

**Comment by KSXGitHub** [comment]
> Well, the https://github.com/actions-rs/toolchain?tab=readme-ov-file action is archived and doesn't seem to support the toml format (or maybe I've done something incorrectly)

This [Reddit thread](https://www.reddit.com/r/rust/comments/186kyra/httpsgithubcomactionsrs_is_archived_what_are_the/) says that [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) could be an alternative. But I'm too busy to adapt right now.

**Comment by ReenigneArcher** [comment]
That action works: https://github.com/ReenigneArcher/pacman-repo-builder/actions/runs/11085060010/job/30801040967

I referenced the following:

- https://github.com/argumentcomputer/arecibo/issues/208
- https://github.com/argumentcomputer/arecibo/pull/215

**Comment by KSXGitHub** [comment]
I hope that your fork works well with new libalpm.

**Comment by ReenigneArcher** [comment]
Note: I'm not going to maintain a fork or anything, although, I'm willing to help you get this up and running again (but I'm not going to create a VM to code on... that is way too much effort and will consume too many resources). It's your project, but you seem to have very little interest maintaining it. Updating all the dependencies would take < 5 minutes... that's all it took me to do locally with no rust experience at all.

If that's too much time for you to spend on it, maybe this should be archived?

**Comment by KSXGitHub** [comment]
I just wanted to know if your CI has started to work.

Like I said, I'm currently very busy. I will update the dependencies again once I have free time.

**Comment by ReenigneArcher** [comment]
I haven't merged any of the dependabot PRs. I can, but need to adjust some things so it doesn't affect this PR. I'll report back.

**Comment by KSXGitHub** [comment]
> I haven't merged any of the dependabot PRs. I can, but need to adjust some things so it doesn't affect this PR. I'll report back.

You just need to update `alpm`.

I'm curious why you wouldn't want to produce your own binary like I suggested though. It should be easy.

**Comment by ReenigneArcher** [comment]
Unfortunately it looks like it will require something besides a dependency update. I guess for makepkg v7.

- pr: https://github.com/ReenigneArcher/pacman-repo-builder/pull/16
- error: https://github.com/ReenigneArcher/pacman-repo-builder/actions/runs/11086213658/job/30803480521?pr=16#step:4:325

Is the only reason for the patch to run makepkg as the root user? If so, is that worth it? Or can you instruct users to create a `builder` user to run everything with?

> I'm curious why you wouldn't want to produce your own binary like I suggested though. It should be easy.

A binary isn't so much effort, but being able to commit is. I don't want to go through the effort of setting up a vm, setup commit signing, installing git, IDE, plugins, etc, etc. when I already have everything setup on my main machine. I'm fine with setting up a dev environment/container that my IDE can SSH into to build or whatever, but to move my whole process is not really worth the time/effort... I'm wondering if these empty file/fixtures should even exist. I haven't looked at the tests super close, but could the tests just create the files when needed? (I understand these files cause absolutely no issue on Linux, so probably it's not worth changing anything)... I'm sure it sounds like not that much effort, but I also have many of my own repos to maintain.

**Comment by KSXGitHub** [comment]
> Unfortunately it looks like it will require something besides a dependency update. I guess for makepkg v7.

The easy way to solve this problem is just add `--unsafe-ignore-unknown-changes`:

```sh
build-pacman-repo patch-makepkg --unsafe-ignore-unknown-changes
```

The hard way: If you can find makepkg v7 on the Internet (since you don't have Arch Linux), you can edit it to remove the root error then copy it to a directory named `patches`. Then, add an item to an array named `MAKEPKG_PATCHES` in file `src/utils/custom_makepkg.rs`.

> Is the only reason for the patch to run makepkg as the root user? If so, is that worth it?

It is so that `build-pacman-repo` can execute `makepkg` in root context (which is the default context of Docker). I was forced to do this hack because `makepkg` doesn't provide an option to allow running in root "for security".

> Or can you instruct users to create a `builder` user to run everything with?

This would require code change for this tool to automatically enter password prompt or something. Which would bring a lot of problems in the future (such as CI hanging, for example). I'd rather not deal with them.

**Comment by KSXGitHub** [comment]
> A binary isn't so much effort, but being able to commit is. I don't want to go through the effort of setting up a vm, setup commit signing, installing git, IDE, plugins, etc, etc.

Can GitHub Web IDE (Codespaces) work with this repo?

Anyway, you can edit the files directly on GitHub UI right? You would need to trigger the CI process and let it build for you. You would need to edit the file `.github/workflows/deploy.yaml`, remove `--locked`, remove steps that you don't need, change the trigger event to something you can control easily, then trigger it.

**Comment by KSXGitHub** [comment]
> I'm wondering if these empty file/fixtures should even exist. I haven't looked at the tests super close, but could the tests just create the files when needed?

~~You may use GitHub Web UI to remove them before clone. After clone, just remove the any test that fails.~~

Actually, just use GitHub Web UI to do everything.

**Pull request closed without merging**
